version: '3'

services:
  postgresql:
    image: postgres:15
    container_name: postgresql
    restart: always
    # ports:
    #   - 5432:5432
    environment:
      - ../env/postgresql.env
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aris -d aris"]
      interval: 5s
      retries: 10
  redis:
    image: bitnami/redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/bitnami/redis/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    env_file:
      - ../env/redis.env


volumes:
  postgresql-data:
    name: postgresql-data
    external: true
  redis-data:
    name: redis-data
    external: true

# docker volume create postgresql-data 
# docker volume create redis-data
# docker compose -f docker/debug-docker-compose-without-minio.yml up -d