version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u$$MYSQL_USER -p$$MYSQL_PASSWORD" ]
      interval: 5s
      retries: 10
    env_file:
      - ../env/mysql.env
  redis:
    image: bitnami/redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/bitnami/redis/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    env_file:
      - ../env/redis.env
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9090"
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3
    env_file:
      - ../env/minio.env


volumes:
  mysql-data:
    name: mysql-data
    external: true
  redis-data:
    name: redis-data
    external: true
  meilisearch-data:
    name: meilisearch-data
    external: true
  minio-data:
    name: minio-data
    external: true

# docker volume create mysql-data 
# docker volume create meilisearch-data
# docker volume create minio-data
# docker volume create redis-data
# docker compose -f docker/debug-docker-compose.yml up -d