version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    # ports:
    #   - 3306:3306
    env_file:
      - ../env/mysql.env
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u$$MYSQL_USER -p$$MYSQL_PASSWORD" ]
      interval: 5s
      retries: 10

  redis:
    image: bitnami/redis:latest
    container_name: redis
    restart: always
    # ports:
    #   - 6379:6379
    env_file:
      - ../env/redis.env
    volumes:
      - redis-data:/bitnami/redis/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    
  aris-db-migrate:
    image: ghcr.io/hcd233/aris-blog-api:master
    container_name: aris-db-migrate
    restart: "no"
    env_file:
      - ../env/api.env
    depends_on:
      mysql:
        condition: service_healthy
    command: ["/app/aris-blog-api", "database", "migrate"]

  aris-blog-api:
    image: ghcr.io/hcd233/aris-blog-api:master
    container_name: aris-blog-api
    restart: always
    ports:
      - 8170:8080
    env_file:
      - ../env/api.env
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      aris-db-migrate:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080"]
      interval: 10s
      timeout: 5s
      retries: 5

    command: ["/app/aris-blog-api", "server", "start", "--host", "0.0.0.0", "--port", "8080"]

volumes:
  mysql-data:
    name: mysql-data
    external: true
  redis-data:
    name: redis-data
    external: true

# docker volume create mysql-data 
# docker volume create redis-data
# docker compose -f docker/docker-compose.yml up -d