version: '3'

services:
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    restart: always
    # ports:
    #   - 7700:7700
    env_file:
      - ../env/meilisearch.env
    volumes:
      - meilisearch-data:/data.ms
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    # ports:
    #   - 3306:3306
    env_file:
      - ../env/mysql.env
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u$$MYSQL_USER -p$$MYSQL_PASSWORD" ]
      interval: 5s
      retries: 10

  redis:
    image: bitnami/redis:latest
    container_name: redis
    restart: always
    # ports:
    #   - 6379:6379
    env_file:
      - ../env/redis.env
    volumes:
      - redis-data:/bitnami/redis/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
    #   - 9000:9000
      - 9090:9090
    env_file:
      - ../env/minio.env
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9090"
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3
    

  aris-db-migrate:
    image: ghcr.io/hcd233/aris-blog-api:master
    container_name: aris-db-migrate
    restart: no
    env_file:
      - ../env/api.env
    depends_on:
      mysql:
        condition: service_healthy
    command: ["/app/aris-blog-api", "database", "migrate"]

  aris-create-index:
    image: ghcr.io/hcd233/aris-blog-api:master
    container_name: aris-create-index
    restart: no
    env_file:
      - ../env/api.env
    depends_on:
      meilisearch:
        condition: service_healthy
    command: ["/app/aris-blog-api", "search", "create"]

  aris-blog-api:
    image: ghcr.io/hcd233/aris-blog-api:master
    container_name: aris-blog-api
    restart: always
    ports:
      - 8170:8080
    env_file:
      - ../env/api.env
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      meilisearch:
        condition: service_healthy
      minio:
        condition: service_healthy
      aris-db-migrate:
        condition: service_completed_successfully
      aris-create-index:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080"]
      interval: 10s
      timeout: 5s
      retries: 5

    command: ["/app/aris-blog-api", "server", "start", "--host", "0.0.0.0", "--port", "8080"]

volumes:
  mysql-data:
    name: mysql-data
    external: true
  redis-data:
    name: redis-data
    external: true
  meilisearch-data:
    name: meilisearch-data
    external: true
  minio-data:
    name: minio-data
    external: true

# docker volume create mysql-data 
# docker volume create redis-data
# docker volume create meilisearch-data
# docker volume create minio-data
# docker compose -f docker/docker-compose.yml up -d