basePath: /
definitions:
  protocol.CallbackResponse:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
  protocol.CreateTagBody:
    properties:
      description:
        type: string
      name:
        type: string
      slug:
        type: string
    required:
    - name
    - slug
    type: object
  protocol.CreateTagResponse:
    type: object
  protocol.DeleteTagResponse:
    type: object
  protocol.GetTagInfoResponse:
    properties:
      tag:
        $ref: '#/definitions/protocol.Tag'
    type: object
  protocol.HTTPResponse:
    properties:
      data: {}
      error:
        type: string
    type: object
  protocol.ListTagsResponse:
    properties:
      pageInfo:
        $ref: '#/definitions/protocol.PageInfo'
      tags:
        items:
          $ref: '#/definitions/protocol.Tag'
        type: array
    type: object
  protocol.LoginResponse:
    properties:
      redirectURL:
        type: string
    type: object
  protocol.PageInfo:
    properties:
      page:
        type: integer
      pageSize:
        type: integer
      total:
        type: integer
    type: object
  protocol.RefreshTokenBody:
    properties:
      refreshToken:
        type: string
    required:
    - refreshToken
    type: object
  protocol.RefreshTokenResponse:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
  protocol.Tag:
    properties:
      createdAt:
        type: string
      description:
        type: string
      likes:
        type: integer
      name:
        type: string
      slug:
        type: string
      tagID:
        type: integer
      updatedAt:
        type: string
      userID:
        type: integer
    type: object
  protocol.UpdateTagBody:
    properties:
      description:
        type: string
      name:
        type: string
      slug:
        type: string
    required:
    - name
    - slug
    type: object
  protocol.UpdateTagResponse:
    type: object
host: 9.134.115.68:8170
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Aris-blog API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Aris-blog
  version: "1.0"
paths:
  /v1/oauth2/github/callback:
    get:
      consumes:
      - application/json
      description: 处理Github OAuth2回调请求,验证code和state
      parameters:
      - description: 授权码
        in: query
        name: code
        required: true
        type: string
      - description: 状态码
        in: query
        name: state
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/protocol.CallbackResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/protocol.CallbackResponse'
      summary: 处理Github OAuth2回调
      tags:
      - oauth2
  /v1/oauth2/github/login:
    get:
      consumes:
      - application/json
      description: 处理Github OAuth2登录请求,返回重定向URL
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/protocol.LoginResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/protocol.LoginResponse'
      summary: 处理Github OAuth2登录
      tags:
      - oauth2
  /v1/tag:
    post:
      consumes:
      - application/json
      description: 创建标签
      parameters:
      - description: 创建标签请求体
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/protocol.CreateTagBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/protocol.HTTPResponse'
            - properties:
                data:
                  $ref: '#/definitions/protocol.CreateTagResponse'
                error:
                  type: object
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/protocol.HTTPResponse'
            - properties:
                data:
                  type: object
                error:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 创建标签
      tags:
      - tag
  /v1/tag/{tagSlug}:
    delete:
      consumes:
      - application/json
      description: 删除标签
      parameters:
      - description: 标签slug
        in: path
        name: tagSlug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/protocol.HTTPResponse'
            - properties:
                data:
                  $ref: '#/definitions/protocol.DeleteTagResponse'
                error:
                  type: object
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/protocol.HTTPResponse'
            - properties:
                data:
                  type: object
                error:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 删除标签
      tags:
      - tag
    get:
      consumes:
      - application/json
      description: 根据标签slug获取标签详细信息
      parameters:
      - description: 标签slug
        in: path
        name: tagSlug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/protocol.HTTPResponse'
            - properties:
                data:
                  $ref: '#/definitions/protocol.GetTagInfoResponse'
                error:
                  type: object
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/protocol.HTTPResponse'
            - properties:
                data:
                  type: object
                error:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 获取标签信息
      tags:
      - tag
    put:
      consumes:
      - application/json
      description: 更新标签
      parameters:
      - description: 标签slug
        in: path
        name: tagSlug
        required: true
        type: string
      - description: 更新标签请求体
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/protocol.UpdateTagBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/protocol.HTTPResponse'
            - properties:
                data:
                  $ref: '#/definitions/protocol.UpdateTagResponse'
                error:
                  type: object
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/protocol.HTTPResponse'
            - properties:
                data:
                  type: object
                error:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 更新标签
      tags:
      - tag
  /v1/tags:
    get:
      consumes:
      - application/json
      description: 获取标签列表
      parameters:
      - in: query
        minimum: 1
        name: page
        required: true
        type: integer
      - in: query
        maximum: 50
        minimum: 1
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/protocol.HTTPResponse'
            - properties:
                data:
                  $ref: '#/definitions/protocol.ListTagsResponse'
                error:
                  type: object
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/protocol.HTTPResponse'
            - properties:
                data:
                  type: object
                error:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 列出标签
      tags:
      - tag
  /v1/token/refresh:
    post:
      consumes:
      - application/json
      description: 刷新令牌
      parameters:
      - description: 刷新令牌请求体
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/protocol.RefreshTokenBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/protocol.HTTPResponse'
            - properties:
                data:
                  $ref: '#/definitions/protocol.RefreshTokenResponse'
                error:
                  type: object
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/protocol.HTTPResponse'
            - properties:
                data:
                  type: object
                error:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 刷新令牌
      tags:
      - token
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
